services:
  nginx:
    extends:
      file: ./docker_compose/nginx.yml
      service: nginx
    depends_on:
      auth_service:
        condition: service_healthy
      frontend:
        condition: service_started
    ports:
      - "${APP__PORT}:80"

  auth_service:
    extends:
      file: ./docker_compose/auth_service.yml
      service: auth_service
    env_file:
      - ./.env
    expose:
      - "${UVICORN__PORT}"
    depends_on:
      redis:
        condition: service_healthy

  frontend:
    extends:
      file: ./docker_compose/frontend.yml
      service: frontend
    env_file:
      - ./.env
    expose:
      - "8080"

  redis:
    extends:
      file: ./docker_compose/redis.yml
      service: redis
    expose:
      - "${REDIS__PORT}"
    volumes:
      - redis-storage:/data
    env_file:
      - ./.env

volumes:
  redis-storage:
